export const SYSTEM_SET_MESSAGE = 'SYSTEM_SET_MESSAGE';
export const SYSTEM_CLEAR_MESSAGE = 'SYSTEM_CLEAR_MESSAGE';

export const VM_IN_PROGRESS = 'VM_IN_PROGRESS';

export const VM_LIST_INSTANCES = 'VM_LIST_INSTANCES';
export const VM_SELECT_INSTANCE = 'VM_SELECT_INSTANCE';

export const VM_CREATE_INSTANCE = 'VM_CREATE_INSTANCE';
export const VM_DELETE_INSTANCE = 'VM_DELETE_INSTANCE';

export const VM_START_INSTANCE = 'VM_START_INSTANCE';
export const VM_RESET_INSTANCE = 'VM_RESET_INSTANCE';
export const VM_STOP_INSTANCE = 'VM_STOP_INSTANCE';

export const VM_STREAMER_MAPPING = 'VM_STREAMER_MAPPING';